version: '2'
services:
  database:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]

  proxy:
    image: nginx:1.13.6-alpine
    ports:
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tls/nginx.key:/etc/nginx/nginx.key:ro
      - ./tls/nginx.crt:/etc/nginx/nginx.crt:ro
    depends_on: [ conjur ]

  client:
    image: conjurinc/cli5
    depends_on: [ proxy ]
    entrypoint: sleep
    command: infinity
