# config file version
apiVersion: 1
# list of datasources to insert/update
datasources:
  # <string, required> name of the datasource. Required
- name: My datasource
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
  # uid: my_unique_uid
  # <string> url
  url: 
  user: 
  # <string> database name
  database: postgres
  # <bool> allow updating provisioned dashboards from the UI
  allowUiUpdates: true
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in jsonData
  jsonData:
    sslmode: 'disable' # disable/require/verify-ca/verify-full
    postgresVersion: 1200 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
    timescaledb: false
  secureJsonData:
    # <string> database password, if used
    password: ""
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
